import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatAmount, formatBasisPoints, formatDuration, shortenAddress, } from '../lib/formatters.js';
import { LoanStatusBadge } from './LoanStatusBadge.js';
export const LoanSummaryCard = ({ loan }) => {
    // Simple interest calculation: Principal + floor(Principal * Rate / 10000)
    const interestAmount = (loan.amount * loan.interestRateBasisPoints) / 10000n;
    const totalRepaymentObligation = loan.amount + interestAmount;
    return (_jsxs("div", { className: "loan-summary-card", children: [_jsxs("div", { className: "card-header", children: [_jsxs("div", { children: [_jsx("h2", { children: "Active Loan Agreement" }), _jsx("span", { className: "card-subtitle", children: "Public Agreement Terms Recorded on Midnight Ledger" })] }), _jsx(LoanStatusBadge, { statusText: loan.statusText })] }), _jsxs("div", { className: "summary-metrics-grid", children: [_jsxs("div", { className: "summary-metric-card primary", children: [_jsx("span", { className: "metric-label", children: "Principal Amount" }), _jsx("span", { className: "metric-value-lg", children: formatAmount(loan.amount) }), _jsx("span", { className: "metric-subtext", children: "Requested borrowing capital" })] }), _jsxs("div", { className: "summary-metric-card", children: [_jsx("span", { className: "metric-label", children: "Interest Rate" }), _jsx("span", { className: "metric-value-lg", children: formatBasisPoints(loan.interestRateBasisPoints) }), _jsxs("span", { className: "metric-subtext", children: [loan.interestRateBasisPoints.toString(), " Basis Points (Simple Interest)"] })] }), _jsxs("div", { className: "summary-metric-card", children: [_jsx("span", { className: "metric-label", children: "Total Repayment Due" }), _jsx("span", { className: "metric-value-lg", children: formatAmount(totalRepaymentObligation) }), _jsxs("span", { className: "metric-subtext", children: ["Principal + ", formatAmount(interestAmount), " interest"] })] }), _jsxs("div", { className: "summary-metric-card", children: [_jsx("span", { className: "metric-label", children: "Loan Duration" }), _jsx("span", { className: "metric-value-lg", children: formatDuration(loan.durationBlocks) }), _jsx("span", { className: "metric-subtext", children: "Ledger blocks until maturity" })] })] }), _jsxs("div", { className: "parties-container", children: [_jsxs("div", { className: "party-row", children: [_jsxs("div", { className: "party-role", children: [_jsx("span", { className: "role-tag borrower-tag", children: "BORROWER" }), _jsx("span", { className: "party-name", children: "Borrower Public Key" })] }), _jsx("code", { className: "party-key", title: loan.borrower, children: shortenAddress(loan.borrower) })] }), _jsxs("div", { className: "party-row", children: [_jsxs("div", { className: "party-role", children: [_jsx("span", { className: "role-tag lender-tag", children: "LENDER" }), _jsx("span", { className: "party-name", children: "Designated Lender" })] }), _jsx("code", { className: "party-key", title: loan.lender ?? undefined, children: shortenAddress(loan.lender) })] })] })] }));
};
