// Canonical typed client lifecycle API & models
export {
  LoanErrorCode,
  LoanApiError,
  mapContractErrorToApiError,
  LoanStatus,
  type LoanStatusText,
  type LoanDetailsModel,
  bytesToHex,
  hexToBytes,
  areByteArraysEqual,
  loanStatusToText,
  mapLedgerToLoanDetails,
  type CreateLoanResult,
  type VerifyLoanEligibilityResult,
  type VerifyEligibilityWithWitnessParams,
  verifyLoanEligibilityWithWitness,
  type FundLoanResult,
  type RepayLoanResult,
  type SettleLoanResult,
  type LifecycleGuardResult,
  canVerifyEligibility,
  canFundLoan,
  canRepayLoan,
  canSettleLoan,
  createLoan,
  verifyLoanEligibility,
  fundLoan,
  repayLoan,
  type RepayLoanAgreementParams,
  repayLoanAgreement,
  settleLoan,
  getLoanStatus,
  getLoanDetails,
  LoanDesk,
} from './loan-api.js';

// Lower-level runtime execution utilities & witness providers
export {
  createEligibilityWitnessProvider,
  initializeLoanContract,
  type InitializeLoanParams,
  type InitializeLoanResult,
  createLoanRequest,
  type CreateLoanRequestParams,
  type CreateLoanRequestResult,
  executeEligibilityProof,
  type ExecuteEligibilityProofParams,
  type EligibilityProofResult,
  calculateRepaymentObligation,
  fundLoan as executeFundLoan,
  repayLoan as executeRepayLoan,
  settleLoan as executeSettleLoan,
  type FundLoanParams,
  type RepayLoanParams,
  type SettleLoanParams,
} from './eligibility-client.js';

